### ISSUE TITLE
Default image size "small" is too small

### ISSUE THREAD

**Issue by tomdxw** [jmau111/jm-twitter-cards#86]
The default size for images in `twitter:image` is "small":

https://github.com/jmau111/jm-twitter-cards/blob/f4b2792a0cdbcbf7a91abec6d1c499ecf4d517ed/views/settings.php#L68-L79

This leads to Twitter using a very small version of the featured image. And this leads to a very blurry image being displayed to Twitter users (at least in desktop browsers).

I'm actually unclear on why it would be beneficial to serve a smaller image to Twitter when Twitter processes the image to make it the right size. So I would either suggest changing the default to "web", or removing the option entirely and serving a big image.

**Comment by jmau111** [comment]
merged in trunk ;)
