### ISSUE TITLE
Ability to set default image size?

### ISSUE THREAD

**Issue by taofik-nos** [jmau111/jm-twitter-cards#99]
Hello, thanks for the great plugin.

Is it possible to allow setting custom default size ? (from the defined wordpress image sizes)
Sometimes the image added as post image is too large for twitter.

In the tutorial video I can see an option for that but it doesn't seem to exist in the plugin.

Thanks!

**Comment by jmau111** [comment]
@taofik-nos hello, I would recommend using the metabox for that instead. You can set a different image than the featured image as twitter card image.

**Comment by jmau111** [comment]
I'm closing this cause it's been a month now. Hope the metabox solution work.
